services:
  mongodb:
    container_name: 'vtt-mongodb'
    env_file:
      - .env
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=${DATABASE_NAME}'
      - 'MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASS}'
      - 'MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER}'
    ports:
      - '27018:27017'
    volumes:
      - 'mongodb_data:/data/db'

volumes:
  mongodb_data: